### ISSUE TITLE
What dependencies am I missing to run simple sample code after just installing ib-ruby 0.9.2?

### ISSUE THREAD

**Issue by mdwin01** [ib-ruby/ib-ruby#124]
What dependencies am I missing to run simple sample code after just installing ib-ruby 0.9.2?

1) I'm trying to run IBInfo1.rb which has this sample code from the readme:
```
#require 'rubygems'
#require 'active_model'
#require 'active_model_serializers'
require 'activemodel-serializers-xml'
require 'ib'


ib = IB::Connection.new :port => 7496
ib.subscribe(:Alert, :AccountValue) { |msg| puts msg.to_human }
ib.send_message :RequestAccountData
ib.wait_for :AccountDownloadEnd

ib.subscribe(:OpenOrder) { |msg| puts "Placed: #{msg.order}!" }
ib.subscribe(:ExecutionData) { |msg| puts "Filled: #{msg.execution}!" }
```

2) If I only 
`require 'ib' `
I get:
C:\Dropbox\Trading>ruby IBInfo1.rb
_C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib/base.rb:9:in `<class:Base>': uninitialized constant Active
Model::Serializers::Xml (NameError)
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib/base.rb:4:in `<module:IB>'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib/base.rb:1:in `<top (required)>'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib/model.rb:2:in `<top (required)>'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib/models.rb:1:in `<top (required)>'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib/requires.rb:8:in `<top (required)>'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib.rb:22:in `<top (required)>'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from IBInfo1.rb:4:in `<main>'_

3) Because of 
_uninitialized constant ActiveModel::Serializers::Xml (NameError)         from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib/base.rb:4_

I went ahead and got activemodel-serializers-xml gem

C:\Dropbox\Trading>gem install activemodel-serializers-xml
Fetching: activemodel-serializers-xml-1.0.2.gem (100%)
Successfully installed activemodel-serializers-xml-1.0.2
Parsing documentation for activemodel-serializers-xml-1.0.2
Installing ri documentation for activemodel-serializers-xml-1.0.2
Done installing documentation for activemodel-serializers-xml after 0 seconds
1 gem installed

and active_model_serializers gem

C:\Dropbox\Trading>gem install active_model_serializers
Successfully installed active_model_serializers-0.10.7
Parsing documentation for active_model_serializers-0.10.7
Done installing documentation for active_model_serializers after 1 seconds
1 gem installed

plus added
`require 'activemodel-serializers-xml'`
in my code

4) Now running my code still does not get passed
`require 'ib'`

here's the stack trace:

C:\Dropbox\Trading>ruby IBInfo1.rb
```
C:/ruby225/lib/ruby/gems/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validations/format.rb:39:in `check_options
_validity': The provided regular expression is using multiline anchors (^ or $), which may present a security risk.
 Did you mean to use \A and \z, or forgot to add the :multiline => true option? (ArgumentError)
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validations/format.rb:20:in `
check_validity!'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validator.rb:141:in `initiali
ze'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validations/with.rb:82:in `ne
w'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validations/with.rb:82:in `bl
ock in validates_with'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validations/with.rb:81:in `ea
ch'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validations/with.rb:81:in `va
lidates_with'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/activemodel-5.0.0.1/lib/active_model/validations/format.rb:109:in
`validates_format_of'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/models/ib/contract_detail.rb:68:in `<class:Contr
actDetail>'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/models/ib/contract_detail.rb:4:in `<module:IB>'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/models/ib/contract_detail.rb:1:in `<top (require
d)>'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib/models.rb:3:in `<top (required)>'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib/requires.rb:8:in `<top (required)>'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/ruby225/lib/ruby/gems/2.2.0/gems/ib-ruby-0.9.2/lib/ib.rb:22:in `<top (required)>'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/ruby225/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from IBInfo1.rb:5:in `<main>'
```

5) Setup:
a) OS: Windows 8
b) TWS 970
c) Ruby: ruby 2.2.5p319 (2016-04-26 revision 54774) [i386-mingw32]
d) Ruby gems:
actionpack (5.0.0.1)
actionview (5.0.0.1)
active_model_serializers (0.10.7)
activemodel (5.0.0.1)
activemodel-serializers-xml (1.0.2)
activerecord (5.0.0.1)
activesupport (5.0.0.1)
ib-ruby (0.9.2)

**Comment by topofocus** [comment]
Hi,
this bug is a consequence of the weird path rails went along.

XML is used for processing of AccountAliases and FlexQueries.
unless you don't rely on that, its safe to comment the xml-dependencies (Gemfile, /lib/ib/base.rb).

For development, I strongly suggest to install the gem by cloning the git-archive as described in the [wiki](https://github.com/ib-ruby/ib-ruby/wiki/Setup-Ruby-and-Install-the-Program)  or fetch the zip  if the [Release 0.92](https://github.com/ib-ruby/ib-ruby/releases). Comments in the messages-section are quite helpful. 

Do you need native rails support?

Otherwise just use the code from the master branch. 

It would be interesting to know, if its running in a windows environment. The Gem 0.97 is ready for release. Some Tests in Windows are helpful.


Greetings
hartmut
