### ISSUE TITLE
Problem with scanner

### ISSUE THREAD

**Issue by JothamB** [ib-ruby/ib-ruby#140]
I try this code following the example scanner_data:

```
#!/usr/bin/ruby

require "ib-ruby"

ib = IB::Connection.new(:port => 7497) do |gw|
        gw.subscribe(:Alert) {|msg| puts msg.to_human}
        gw.subscribe(IB::Messages::Incoming::ScannerData) {|msg| puts msg}
end

sleep 5
ib.send_message(IB::Messages::Outgoing::RequestScannerSubscription.new(:scan_code => "TOP_PERC_GAIN", :instrument => "STK"))
sleep 5
```

I get nothing. No error no data. The program sleeps and then exits with code 0.

I'm stuck here. What am I missing ? How can I set a simple scanner that returns data ?

**Comment by topofocus** [comment]
Hi Jotham,

1. have you been able to run the example (scanner_data) ?

2. which TWS-version are you using?

**Comment by JothamB** [comment]
Running the example gave the following error:

```
#<Thread:0x000055e5a753fda8@/var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:365 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	10: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:365:in `block in start_reader'
	 9: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:295:in `process_messages'
	 8: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:385:in `process_message'
	 7: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/socket.rb:101:in `decode_message'
	 6: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:397:in `block in process_message'
	 5: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:397:in `new'
	 4: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/abstract_message.rb:39:in `initialize'
	 3: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `load'
	 2: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `new'
	 1: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `initialize'
/var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:26:in `block in load': undefined local variable or method `socket' for #<IB::Messages::Incoming::ScannerData:0x000055e5a7409f60> (NameError)
Traceback (most recent call last):
	10: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:365:in `block in start_reader'
	 9: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:295:in `process_messages'
	 8: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:385:in `process_message'
	 7: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/socket.rb:101:in `decode_message'
	 6: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:397:in `block in process_message'
	 5: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:397:in `new'
	 4: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/abstract_message.rb:39:in `initialize'
	 3: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `load'
	 2: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `new'
	 1: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `initialize'
/var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:26:in `block in load': undefined local variable or method `socket' for #<IB::Messages::Incoming::ScannerData:0x000055e5a7409f60> (NameError)
```

I'm using TWS 972.1v

**Comment by topofocus** [comment]
Ah. 
The script uses the old IB-protocol-notation. 
socket is exchanged by »buffer«

I created a feature-branch  »scanner«.
Can you please switch to it and repeat the exercise?

**Comment by JothamB** [comment]
Still getting the same error ..

**Comment by JothamB** [comment]
My bad .. I didn't update the gem to the scanner branch ..

After updating the gem I got a different error:

```
#<Thread:0x0000561dac1d08d8@/var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:365 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	10: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:365:in `block in start_reader'
	 9: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:295:in `process_messages'
	 8: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:385:in `process_message'
	 7: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/socket.rb:101:in `decode_message'
	 6: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:397:in `block in process_message'
	 5: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:397:in `new'
	 4: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/abstract_message.rb:39:in `initialize'
	 3: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `load'
	 2: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `new'
	 1: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `initialize'
/var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:26:in `block in load': undefined method `read_int' for #<Array:0x0000561dabeb3b00> (NoMethodError)
Traceback (most recent call last):
	10: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:365:in `block in start_reader'
	 9: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:295:in `process_messages'
	 8: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:385:in `process_message'
	 7: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/socket.rb:101:in `decode_message'
	 6: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:397:in `block in process_message'
	 5: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/connection.rb:397:in `new'
	 4: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/abstract_message.rb:39:in `initialize'
	 3: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `load'
	 2: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `new'
	 1: from /var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:25:in `initialize'
/var/lib/gems/2.5.0/gems/ib-ruby-0.9.7.2/lib/ib/messages/incoming/scanner_data.rb:26:in `block in load': undefined method `read_int' for #<Array:0x0000561dabeb3b00> (NoMethodError)
```

**Comment by JothamB** [comment]
I got to a point I really needed this feature so I stepped in and figured it myself.

After modifying messages/incoming/scanner_data.rb the example worked for me.

This is how I did it:

```
module IB
  module Messages
    module Incoming

      # This method receives the requested market scanner data results.
      # ScannerData contains following @data:
      # :request_id - The ID of the request to which this row is responding
      # :count - Number of data points returned (size of :results).
      # :results - an Array of Hashes, each hash contains a set of
      #            data about one scanned Contract:
      #            :contract - a full description of the contract (details).
      #            :distance - Varies based on query.
      #            :benchmark - Varies based on query.
      #            :projection - Varies based on query.
      #            :legs - Describes combo legs when scan is returning EFP.
      ScannerData = def_message [20, 3],
                                [:request_id, :int], # request id
                                [:count, :int]
        class ScannerData
        attr_accessor :results
        def load
                super
                @results = Array.new
                i = 0
                @data[:count].times do
                        @results.push Hash[:rank => buffer[i].to_i, :contract => Contract.build(:con_id => buffer[i + 1].to_i, :symbol => buffer[i + 2], :sec_type => buffer[i + 3], :expiry => buffer[i + 4], :strike => buffer[i + 5].to_f, :right => buffer[i + 6], :exchange => buffer[i + 7], :currency => buffer[i + 8], :local_symbol => buffer[i + 9], :contract_detail => IB::ContractDetail.new(:market_name => buffer[i + 10], :trading_class => buffer[i + 11])), :distance => buffer[i + 12], :benchmark => buffer[i + 13], :projection => buffer[i + 14], :legs => buffer[i + 15]]
                        i += 16
                end
        end
      end # ScannerData

    end # module Incoming
  end # module Messages
end # module IB
```

**Comment by JothamB** [comment]
As far as I'm concerned this issue is closed.
It's up to you to modify the repository. Although this code runs the example, I'm not sure if this is a perfect solution for all scanner options.
Anyway, the principle is treating buffer as an array and building the @results array accordingly.
